### ISSUE TITLE
[Bug Report] api.proxyman.app is down

### ISSUE THREAD

**Issue by laggardkernel** [NghiaTranUIT/artify-macos#68]
Sorry, it's my first time trying this app. Does the app still being maintained?

**Comment by NghiaTranUIT** [comment]
Hey @laggardkernel 

Sorry that the Artify server is completely shut down. I don't have intention to maintain it.

Feel free to fork and deploy by your own 👍

**Comment by laggardkernel** [comment]
Got it. Thanks for your reply.
